<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Natsx.Controller.Core/Natsx.Controller.Core.csproj" />
    <ProjectReference Include="../Natsx.Controller.Protocol/Natsx.Controller.Protocol.csproj" />
    <ProjectReference Include="../Natsx.Controller.Connection/Natsx.Controller.Connection.csproj" />
    <ProjectReference Include="../Natsx.Controller.VirtualGamepad/Natsx.Controller.VirtualGamepad.csproj" />
    <ProjectReference Include="../Natsx.Controller.Transport.Bluetooth/Natsx.Controller.Transport.Bluetooth.csproj" />
    <ProjectReference Include="../Natsx.Controller.Transport.Usb/Natsx.Controller.Transport.Usb.csproj" />
    <ProjectReference Include="../Natsx.Controller.Transport.Wifi/Natsx.Controller.Transport.Wifi.csproj" />
    <ProjectReference Include="../Natsx.Controller.Trust.Windows/Natsx.Controller.Trust.Windows.csproj" />
  </ItemGroup>
</Project>
