<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Natsx.Controller.Core/Natsx.Controller.Core.csproj" />
    <ProjectReference Include="../Natsx.Controller.Protocol/Natsx.Controller.Protocol.csproj" />
    <ProjectReference Include="../Natsx.Controller.Connection/Natsx.Controller.Connection.csproj" />
  </ItemGroup>
</Project>
